version: 2
executorType: docker
containerInfo:
  - image: buildpack-deps:jessie
stages:
  build:
    workDir: ~/my-project
    steps:
      - type: checkout
      - type: shell
        name: Install Docker Client
        command: |
          curl -L -o /tmp/docker.tgz https://get.docker.com/builds/Linux/x86_64/docker-1.13.1.tgz
          tar -xz -C /tmp -f /tmp/docker.tgz
          mv /tmp/docker/docker* /usr/bin/

          curl -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
          chmod +x  /usr/bin/docker-compose
      - type: setup-docker-engine
        reusable: true
        exclusive: false
      - type: shell
        command: docker info
      - type: shell
        command: bin/ci
      - type: deploy
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            bin/deploy
          fi
