version: '2'
services:
  web: &web
    build:
      context: .
      args:
        - LOCAL_BUILD=true
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:@db
      - PORT=3000
      - HOST=0.0.0.0
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - db
      - webpack
    networks:
      - my-net

  spring:
    <<: *web
    # TODO run spring server
    command: watch echo
    environment:
      - DATABASE_URL=postgres://postgres:@db
      - CHROME_URL=$CHROME_URL
      - CAPYBARA_SERVER_PORT=3001
      - CAPYBARA_APP_HOST=$CAPYBARA_APP_HOST
      - BS_USERNAME=$BS_USERNAME
      - BS_AUTHKEY=$BS_AUTHKEY
      - CI=$CI
      - IDOBATA_HOOK_URL=$IDOBATA_HOOK_URL
    ports:
      - 3001:3001
    depends_on:
      - db
      - webpack
      - chrome

  webpack:
    <<: *web
    command: npm run server
    ports:
      - 3808:3808
    environment: []
    depends_on: []

  chrome:
    image: mtsmfm/standalone-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 5900:5900
    networks:
      - my-net

  db:
    image: postgres:9.5.4
    networks:
      - my-net

networks:
  my-net:
