version: '2'
services:
  web: &web
    build:
      context: .
      args:
        - LOCAL_BUILD=true
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:@db
      - PORT=3000
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - db

  spring:
    <<: *web
    # TODO run spring server
    command: watch echo
    environment:
      - DATABASE_URL=postgres://postgres:@db
      - CHROME_URL=$CHROME_URL
      - CAPYBARA_SERVER_PORT=3001
      - CAPYBARA_APP_HOST=$CAPYBARA_APP_HOST
      - BS_USERNAME=$BS_USERNAME
      - BS_AUTHKEY=$BS_AUTHKEY
      - CI=$CI
    ports:
      - 3001:3001

  browserstacklocal:
    image: mtsmfm/browserstacklocal
    command: $BS_AUTHKEY
    depends_on:
      - spring

  db:
    image: postgres:9.5.4
