version: '2'
services:
  web: &web
    build:
      context: .
      args:
        - LOCAL_BUILD=true
    volumes:
      - .:/app
      - ~/ghq:/ghq
    environment:
      - DATABASE_URL=postgres://postgres:@db
      - PORT=3000
      - HOST=0.0.0.0
      #- BUNDLE_LOCAL__RAILS=/ghq/github.com/mtsmfm/rails
      #- BUNDLE_DISABLE_LOCAL_BRANCH_CHECK=true
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - db
      - client
      - chrome

  client: &client
    <<: *web
    command: npm run server
    ports:
      - 3808:3808
    environment: []
    depends_on: []

  relay:
    <<: *client
    command: yarn run relay -- --watch
    ports: []

  chrome:
    image: selenium/standalone-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 5900:5900
    stop_signal: kill

  db:
    image: postgres:9.5.4
