version: '2'
services:
  web: &web
    build:
      context: .
      args:
        - RAILS_ENV=
        - APP_DIR=/app
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle
      - node_modules:/app/node_modules
      - front_node_modules:/app/frontend/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    links:
      - db

  spring:
    <<: *web
    # TODO run spring server
    command: watch echo
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db
      - CHROME_URL=$CHROME_URL
      - CAPYBARA_SERVER_PORT=3001
      - CAPYBARA_APP_HOST=$CAPYBARA_APP_HOST
      - BS_USERNAME=$BS_USERNAME
      - BS_AUTHKEY=$BS_AUTHKEY
      - CI=$CI
    ports:
      - 3001:3001

  browserstacklocal:
    image: mtsmfm/browserstacklocal
    command: $BS_AUTHKEY
    links:
      - spring

  db:
    image: postgres:9.5.4

volumes:
  bundle:
  node_modules:
  front_node_modules:
