/**
 * Janjan API
 * Janjan API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export interface Tile {
    /**
     * unique identifier of tile
     */
    id?: number;

    /**
     * kind of tile
     */
    kind?: Tile.KindEnum;

    /**
     * order of tile
     */
    order?: number;

}
export namespace Tile {
    export enum KindEnum {
        East = <any> 'east',
        South = <any> 'south',
        West = <any> 'west',
        North = <any> 'north',
        Chun = <any> 'chun',
        Hatsu = <any> 'hatsu',
        Haku = <any> 'haku',
        Man1 = <any> 'man_1',
        Man2 = <any> 'man_2',
        Man3 = <any> 'man_3',
        Man4 = <any> 'man_4',
        Man5 = <any> 'man_5',
        Man6 = <any> 'man_6',
        Man7 = <any> 'man_7',
        Man8 = <any> 'man_8',
        Man9 = <any> 'man_9',
        Sou1 = <any> 'sou_1',
        Sou2 = <any> 'sou_2',
        Sou3 = <any> 'sou_3',
        Sou4 = <any> 'sou_4',
        Sou5 = <any> 'sou_5',
        Sou6 = <any> 'sou_6',
        Sou7 = <any> 'sou_7',
        Sou8 = <any> 'sou_8',
        Sou9 = <any> 'sou_9',
        Pin1 = <any> 'pin_1',
        Pin2 = <any> 'pin_2',
        Pin3 = <any> 'pin_3',
        Pin4 = <any> 'pin_4',
        Pin5 = <any> 'pin_5',
        Pin6 = <any> 'pin_6',
        Pin7 = <any> 'pin_7',
        Pin8 = <any> 'pin_8',
        Pin9 = <any> 'pin_9'
    }
}
